K3S Settings for bm APIs

diff --git a/main/templates/scripts-bm.yaml b/main/templates/scripts-bm.yaml
--- a/main/templates/scripts-bm.yaml
+++ b/main/templates/scripts-bm.yaml
@@ -2,11 +2,175 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
+  name: script-bm-k3s
+  namespace: skycluster-system
+  labels:
+    skycluster.io/managed-by: skycluster
+    skycluster.io/script-type: sshtask
+    skycluster.io/script-init: bm-k3s-controller
+data:
+  k3s_controller_prob.sh: |
+    #!/bin/bash
+    export USERNAME=`whoami`
+    export K3S_HOME=/home/$USERNAME/k3s
+    export KUBECONFIG=$K3S_HOME/k3s.yaml
+
+    TOKEN=""
+
+    compliant=true
+    declare -A details
+
+    if ! sudo kubectl config view --flatten >/dev/null 2>&1; then
+      compliant=false
+      details["kubectl"]="missing"
+    fi
+
+
+    INTF_NAME=$(ip route get 8.8.8.8 | awk '{print $5; exit}' || true)
+    if [[ -z "$INTF_NAME" ]]; then
+      compliant=false
+      details["interface"]="cannot-detect"
+    else
+      IP_ADDR=$(ip -o -4 addr show "$INTF_NAME" | awk '{print $4}' | cut -d/ -f1 || true)
+      if [[ -z "$IP_ADDR" ]]; then
+        compliant=false
+        details["ip_address"]="cannot-detect"
+      fi
+    fi
+
+    KUBECONFIG=""
+    if $compliant; then
+      KUBECONFIG=$(sudo kubectl config view --flatten | sed "s/127.0.0.1/$IP_ADDR/" | base64 -w0 || true)
+      if [[ -z "$KUBECONFIG" ]]; then
+        compliant=false
+        details["kubeconfig"]="cannot-generate"
+      fi
+    fi
+
+    if [[ ! -f "$K3S_HOME/k3s.yaml" ]]; then
+      compliant=false
+      details["k3s.yaml"]="missing"
+    fi
+
+    if [[ ! -f "/var/lib/rancher/k3s/server/node-token" ]]; then
+      compliant=false
+      details["k3s.token"]="missing"
+    else 
+      TOKEN=`sudo cat /var/lib/rancher/k3s/server/node-token`
+      if [[ -z "$TOKEN" ]]; then
+        compliant=false
+        details["k3s.token"]="missing"
+      fi
+    fi
+
+    # build JSON
+    checks="{"
+      for key in "${!details[@]}"; do
+          checks+="\"$key\":\"${details[$key]}\","
+      done
+    checks="${checks%,}}"
+
+    facts=$(jq -n \
+      --arg token "$TOKEN" \
+      --arg kube_b64 "$KUBECONFIG" \
+      --arg iface "$INTF_NAME" \
+      --arg ip "$IP_ADDR" \
+      --argjson checks "$checks" \
+      '{ 
+        network:{interface:$iface, ip:$ip},
+        kubeconfig:{encoded:$kube_b64, token:$token},
+        checks: $checks
+      }'
+    )
+
+    jq -n --argjson compliant "$compliant" \
+      --argjson facts "$facts" '{compliant: $compliant, facts: $facts}' 
+
+  k3s_controller.sh: |
+    #!/bin/bash
+          
+    export USERNAME=`whoami`
+    export K3S_HOME=/home/$USERNAME/k3s
+    export KUBECONFIG=$K3S_HOME/k3s.yaml
+    export K3S_URL_FILE="https://github.com/k3s-io/k3s/releases/download/v1.33.3+k3s1/k3s"
+    export K3S_BIN="/usr/local/bin"
+
+    mkdir -p $K3S_HOME
+    mkdir -p $K3S_BIN
+    mkdir -p $K3S_HOME/scripts
+    mkdir -p $K3S_HOME/logs
+
+    exec > "$K3S_HOME/logs/k3s-install-$(date +'%Y-%m-%d_%H-%M').log" 2>&1
+
+    export INTF_NAME=$(ip route get 8.8.8.8 | awk '{print $5; exit}')
+    if ! ip -o -4 a show | grep -q $INTF_NAME; then
+      echo "Error: interface not found."
+      exit 1
+    fi
+    export NODE_IP=`ip -o -4 a show $INTF_NAME | awk '{print $4}' | cut -d/ -f1`
+    export PUBLIC_IP=`curl ifconfig.io`
+
+    ADVERTISE_IP=$PUBLIC_IP
+    if [ -z "$PUBLIC_IP" ]; then
+      echo "Failed to retrieve public IP. Use node ip instead."
+      ADVERTISE_IP=$NODE_IP
+    fi
+
+    max_retries=10
+    retry_count=0
+    install_success=false
+    while [ $retry_count -lt $max_retries ]; do
+      if curl --max-time 80 -sfL --retry 3 -C - "$K3S_URL_FILE" -o "$K3S_BIN/k3s"; then 
+        echo "INFO: Downloaded k3s binary"
+        chmod +x "$K3S_BIN/k3s"
+        echo "Installing k3s..."
+        if curl -sfL https://get.k3s.io | \
+          INSTALL_K3S_SKIP_DOWNLOAD=true \
+          K3S_KUBECONFIG_MODE="644" \
+          INSTALL_K3S_EXEC=" \
+            --cluster-cidr __CLUSTER_CIDR__ \
+            --advertise-address $ADVERTISE_IP \
+            --node-ip $NODE_IP \
+            --service-cidr __SERVICE_CIDR__ \
+            --flannel-backend=vxlan \
+            --disable-network-policy \
+            --disable=traefik \
+            --node-label skycluster.io/node-type=control-plane \
+            --node-label skycluster.io/provider-platform=__PROVIDERPLATFORM__ \
+            --node-label skycluster.io/provider-region=__REGION__ \
+            --node-label skycluster.io/provider-identifier=__PROVIDERPLATFORM__-__REGION__-__ZONE__ \
+            --node-label topology.kubernetes.io/region=__PROVIDERPLATFORM__-__REGION__-__ZONE__ \
+            --node-label topology.kubernetes.io/zone=__PROVIDERPLATFORM__-__REGION__-__ZONE__ \
+            --node-label submariner.io/gateway=true" sh -; then
+          install_success=true
+          break
+        else
+          echo "Attempt $(($retry_count + 1)) of $max_retries failed. Retrying..." 
+          retry_count=$(($retry_count + 1))
+          sleep 3
+        fi
+      else
+        echo "Downloading k3s Attempt $(($retry_count + 1)) of $max_retries failed. Retrying..."
+        retry_count=$(($retry_count + 1))
+        sleep 3
+      fi
+    done
+    if [ "$install_success" = false ]; then
+      echo "Error: Failed to install k3s after $max_retries attempts." 
+      exit 1
+    fi
+    sudo cp /etc/rancher/k3s/k3s.yaml $K3S_HOME/k3s.yaml
+    sudo chown $USERNAME $K3S_HOME/k3s.yaml 
+
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
   name: script-bm-setup-gw
   namespace: skycluster-system
   labels:
     skycluster.io/managed-by: skycluster
-    skycluster.io/config-type: bm-gw-setup
+    skycluster.io/script-type: bm-gw-setup
 data:
   env_prepare_static_prob_script.sh: |
     #!/bin/bash
